# Generated by Django 4.2.3 on 2023-09-13 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductCategories',
            new_name='ProductCategory',
        ),
    ]
